// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCCEfpxMx_eIUR64OXiWJ8YkZ7Is1QQn4',
    appId: '1:1006706709630:web:94f4a0db61690603b9742f',
    messagingSenderId: '1006706709630',
    projectId: 'cuidapp-693f2',
    authDomain: 'cuidapp-693f2.firebaseapp.com',
    storageBucket: 'cuidapp-693f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_L2-uZCfjGyqfv7uQUaPvU4Bf0m1rQ9E',
    appId: '1:1006706709630:android:e0800b5f361efd23b9742f',
    messagingSenderId: '1006706709630',
    projectId: 'cuidapp-693f2',
    storageBucket: 'cuidapp-693f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJdTTl-t1v5KyPKeCiGmIoetL-lYKfE_c',
    appId: '1:1006706709630:ios:e55e8da4524c02a8b9742f',
    messagingSenderId: '1006706709630',
    projectId: 'cuidapp-693f2',
    storageBucket: 'cuidapp-693f2.appspot.com',
    iosBundleId: 'com.example.cuidaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJdTTl-t1v5KyPKeCiGmIoetL-lYKfE_c',
    appId: '1:1006706709630:ios:90d0e1813e74f5b1b9742f',
    messagingSenderId: '1006706709630',
    projectId: 'cuidapp-693f2',
    storageBucket: 'cuidapp-693f2.appspot.com',
    iosBundleId: 'com.example.cuidaApp.RunnerTests',
  );
}
